//! Cookie isolation proof — runtime verification that a cookie set in identity A's
//! `RequestContext` is **invisible** to identity B's `RequestContext`.
//!
//! This is the runtime complement to the directory-separation assertion in
//! `profiles_input`. Where `profiles_input` proved that two identities get distinct
//! on-disk storage paths, this example proves that the cookie stores are truly
//! independent at the API level: writing a cookie through A's `CookieManager` does
//! not make it visible through B's `CookieManager`.
//!
//! # Method
//!
//! 1. Create profiles A ("alice-cookie-iso") and B ("bob-cookie-iso") via
//!    `ProfileManager`.
//! 2. Obtain each profile's cookie manager via `ProfileHandle::cookie_manager`.
//! 3. Set a cookie (`mote-isolation-test=present`) in A's cookie manager for
//!    `https://isolation.test`.
//! 4. Pump until `set_cookie`'s async callback fires (confirming the write
//!    landed in the cookie store).
//! 5. Query A's cookie manager with `visit_url_cookies` and assert the cookie IS
//!    present (proves the write actually worked).
//! 6. Query B's cookie manager with `visit_url_cookies` and assert the cookie is
//!    ABSENT (proves isolation holds).
//!
//! The visitors are callback-based (CEF's async model); we use shared `AtomicBool`
//! / `AtomicU32` flags and pump the engine between each async operation so CEF
//! can deliver the callbacks on the UI thread.
//!
//! Run (libcef.so resolves via the crate's `$ORIGIN` rpath; force ozone under X11):
//!
//! ```sh
//! DISPLAY=:1 mise exec -- cargo run -p mote-cef --example cookie_isolation -- \
//!     --ozone-platform=x11
//! ```
//!
//! Exit code 0 with `COOKIE ISOLATION: PASS` is the evidence. A non-zero exit
//! with `FAIL` means isolation is broken — treat this as a MUST-level finding.

#![allow(
    unsafe_code,
    reason = "wrap_set_cookie_callback! and manual CookieVisitor impl use CEF FFI internals; \
              contained within mote-cef per DISCIPLINES.md §1"
)]

use std::process::ExitCode;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use std::time::{Duration, Instant};

use cef::{
    CefString, Cookie, CookieManager, CookieVisitor, ImplCookieManager as _, ImplCookieVisitor,
    ImplSetCookieCallback, SetCookieCallback, WrapCookieVisitor, WrapSetCookieCallback,
    rc::Rc as CefRc, rc::RcImpl, sys, wrap_set_cookie_callback,
};

use mote_cef::{Engine, EngineConfig, IdentityId, ProcessRole, ProfileManager};

// The origin we plant the test cookie under. Must be a valid URL for CEF's
// cookie store keying; we use a synthetic `.test` TLD to avoid any accidental
// network activity.
const COOKIE_URL: &str = "https://isolation.test";
const COOKIE_NAME: &str = "mote-isolation-test";
const COOKIE_VALUE: &str = "present";

/// Pump the engine for `ms` milliseconds, sleeping 4 ms between ticks.
fn pump(engine: &Engine, ms: u64) {
    let start = Instant::now();
    while start.elapsed().as_millis() < u128::from(ms) {
        engine.pump();
        std::thread::sleep(Duration::from_millis(4));
    }
}

/// Pump until `flag` is set or `timeout_secs` elapses.  Returns `true` if the
/// flag was set in time.
fn pump_until(engine: &Engine, flag: &AtomicBool, timeout_secs: u64) -> bool {
    let start = Instant::now();
    loop {
        engine.pump();
        std::thread::sleep(Duration::from_millis(4));
        if flag.load(Ordering::Acquire) {
            return true;
        }
        if start.elapsed().as_secs() >= timeout_secs {
            return false;
        }
    }
}

/// Pump until `flag` is set.  If the flag is not set within `settle_ms`
/// milliseconds, treat that as "completed with zero results" and return `true`
/// anyway.  Use this for cookie visits on stores that may be empty: CEF does
/// not call the visitor callback at all when the store has no matching cookies
/// (even when `visit_url_cookies` returns 1), so a flag that never fires is
/// indistinguishable from "zero cookies found" from the outside.
fn pump_until_or_settle(engine: &Engine, flag: &AtomicBool, settle_ms: u64) -> bool {
    let start = Instant::now();
    loop {
        engine.pump();
        std::thread::sleep(Duration::from_millis(4));
        if flag.load(Ordering::Acquire) {
            return true;
        }
        if start.elapsed().as_millis() >= u128::from(settle_ms) {
            // Treat silence as "zero cookies returned" — mark as done.
            flag.store(true, Ordering::Release);
            return true;
        }
    }
}

/// Set the test cookie in `mgr` for `COOKIE_URL`.  Returns an `AtomicBool`
/// that will be set `true` once the async `SetCookieCallback` fires.
#[allow(
    clippy::transmute_ptr_to_ptr,
    reason = "transmute is generated by the wrap_set_cookie_callback! macro from cef-rs; not our code"
)]
fn schedule_set_cookie(mgr: &CookieManager) -> Arc<AtomicBool> {
    let done = Arc::new(AtomicBool::new(false));

    // Build the cookie object. CEF requires `size` to equal `sizeof(_cef_cookie_t)`,
    // which `Cookie::default()` pre-fills correctly.
    let cookie = Cookie {
        name: CefString::from(COOKIE_NAME),
        value: CefString::from(COOKIE_VALUE),
        // Empty domain/path → CEF uses the URL's host and "/".
        ..Cookie::default()
    };

    let flag = Arc::clone(&done);
    wrap_set_cookie_callback! {
        struct SetDone {
            fired: Arc<AtomicBool>,
        }
        impl SetCookieCallback {
            fn on_complete(&self, _success: ::std::os::raw::c_int) {
                self.fired.store(true, ::std::sync::atomic::Ordering::Release);
            }
        }
    }
    let mut cb = SetDone::new(flag);

    let url = CefString::from(COOKIE_URL);
    mgr.set_cookie(Some(&url), Some(&cookie), Some(&mut cb));

    done
}

// ---------------------------------------------------------------------------
// Manual CookieVisitor implementation.
//
// We implement `ImplCookieVisitor` manually to detect "visit complete" when
// `count_idx + 1 == total` or `total == 0` (empty store).
// ---------------------------------------------------------------------------

struct CountVisitorInner {
    fired: Arc<AtomicBool>,
    matches: Arc<AtomicU32>,
    // Raw pointer to the CEF ref-counted object. Set by `WrapCookieVisitor::wrap_rc`.
    cef_object: *mut RcImpl<sys::_cef_cookie_visitor_t, Self>,
}

impl Clone for CountVisitorInner {
    fn clone(&self) -> Self {
        // SAFETY: CEF only calls `add_ref` / `release` from its own threads.
        // All callback invocations happen on the UI thread, and we only clone
        // inside the `clone` implementation required by the CEF RC model.
        unsafe {
            let rc_impl = &mut *self.cef_object;
            rc_impl.interface.add_ref();
        }
        Self {
            fired: self.fired.clone(),
            matches: self.matches.clone(),
            cef_object: self.cef_object,
        }
    }
}

impl CefRc for CountVisitorInner {
    fn as_base(&self) -> &sys::cef_base_ref_counted_t {
        // SAFETY: `cef_object` is initialised by `wrap_rc` before any CEF call.
        // `RcImpl.cef_object` is `_cef_cookie_visitor_t`, whose first field
        // `base` is `cef_base_ref_counted_t` (asserted at offset 0 in the
        // generated bindings). Borrowing it is safe for the lifetime of `&self`.
        unsafe { &(*self.cef_object).cef_object.base }
    }
}

impl WrapCookieVisitor for CountVisitorInner {
    fn wrap_rc(&mut self, obj: *mut RcImpl<sys::_cef_cookie_visitor_t, Self>) {
        self.cef_object = obj;
    }
}

impl ImplCookieVisitor for CountVisitorInner {
    fn visit(
        &self,
        cookie: Option<&Cookie>,
        count_idx: ::std::os::raw::c_int,
        total: ::std::os::raw::c_int,
        _delete: Option<&mut ::std::os::raw::c_int>,
    ) -> ::std::os::raw::c_int {
        if let Some(c) = cookie {
            let name: String = c.name.to_string();
            if name == COOKIE_NAME {
                self.matches.fetch_add(1, Ordering::Release);
            }
        }
        // Mark done on the last cookie, or immediately when the store is empty
        // (CEF calls visit once with total == 0 for an empty store).
        if total == 0 || count_idx + 1 >= total {
            self.fired.store(true, Ordering::Release);
        }
        1 // continue visiting
    }

    fn get_raw(&self) -> *mut sys::_cef_cookie_visitor_t {
        self.cef_object.cast()
    }
}

/// Visit all cookies for `COOKIE_URL` in `mgr` and count how many are named
/// `COOKIE_NAME`.  Returns a pair of `Arc`s: the visit-complete flag, and the
/// match count.
///
/// CEF's `visit_url_cookies` does not call the visitor at all when the cookie
/// store has zero matching cookies (it returns 0 in that case). We pre-mark
/// `done` if the return value is 0 so callers don't wait for a callback that
/// will never arrive.
fn schedule_visit_cookies(mgr: &CookieManager) -> (Arc<AtomicBool>, Arc<AtomicU32>) {
    let done = Arc::new(AtomicBool::new(false));
    let count = Arc::new(AtomicU32::new(0));

    let mut visitor = CookieVisitor::new(CountVisitorInner {
        fired: Arc::clone(&done),
        matches: Arc::clone(&count),
        cef_object: std::ptr::null_mut(),
    });

    let url = CefString::from(COOKIE_URL);
    // include_http_only = 0 (false; we only set a plain cookie above).
    let queued = mgr.visit_url_cookies(Some(&url), 0, Some(&mut visitor));
    if queued == 0 {
        // CEF returns 0 when there are no matching cookies (or the store is not
        // yet available). In both cases the visitor will never be called, so we
        // mark done immediately. Zero matches is the correct result here.
        done.store(true, Ordering::Release);
    }

    (done, count)
}

#[allow(
    clippy::too_many_lines,
    reason = "linear integration-proof narrative; splitting hurts the end-to-end flow"
)]
fn main() -> ExitCode {
    // STEP 1: process split. Subprocesses must exit here.
    match mote_cef::bootstrap() {
        ProcessRole::Subprocess { exit_code } => {
            return ExitCode::from(u8::try_from(exit_code.clamp(0, 255)).unwrap_or(0));
        }
        ProcessRole::Browser => {}
    }

    // STEP 2: engine.
    let config = EngineConfig {
        no_sandbox: true,
        ..EngineConfig::default()
    };
    let profiles_root = config.cache_path.clone();
    let engine = match Engine::init(&config) {
        Ok(e) => e,
        Err(e) => {
            eprintln!("FAIL: engine init: {e}");
            return ExitCode::FAILURE;
        }
    };

    // STEP 3: two identity profiles.
    let manager = ProfileManager::new(&profiles_root);
    let alice_id = IdentityId::new("alice-cookie-iso").expect("valid id");
    let bob_id = IdentityId::new("bob-cookie-iso").expect("valid id");

    let alice = match manager.get_or_create(&alice_id) {
        Ok(p) => p,
        Err(e) => {
            eprintln!("FAIL: create profile alice: {e}");
            return ExitCode::FAILURE;
        }
    };
    let bob = match manager.get_or_create(&bob_id) {
        Ok(p) => p,
        Err(e) => {
            eprintln!("FAIL: create profile bob: {e}");
            return ExitCode::FAILURE;
        }
    };
    eprintln!(
        "profiles: alice={} bob={}",
        alice.storage_path().display(),
        bob.storage_path().display()
    );

    // Let the freshly-created profile contexts initialise on the UI thread.
    pump(&engine, 400);

    // STEP 4: obtain cookie managers.
    let Some(alice_mgr) = alice.cookie_manager() else {
        eprintln!("FAIL: could not obtain alice's cookie manager");
        return ExitCode::FAILURE;
    };
    let Some(bob_mgr) = bob.cookie_manager() else {
        eprintln!("FAIL: could not obtain bob's cookie manager");
        return ExitCode::FAILURE;
    };
    eprintln!("cookie managers obtained for both profiles, URL={COOKIE_URL}");

    // STEP 5: set cookie in Alice's store.
    let set_done = schedule_set_cookie(&alice_mgr);
    if !pump_until(&engine, &set_done, 10) {
        eprintln!("FAIL: set_cookie callback did not fire within 10 s");
        return ExitCode::FAILURE;
    }
    eprintln!("set_cookie in alice: DONE");

    // STEP 6: verify cookie IS present in Alice's store.
    let (a_visit_done, a_count) = schedule_visit_cookies(&alice_mgr);
    if !pump_until(&engine, &a_visit_done, 10) {
        eprintln!("FAIL: alice visit_url_cookies did not complete within 10 s");
        return ExitCode::FAILURE;
    }
    let alice_hits = a_count.load(Ordering::Acquire);
    eprintln!(
        "alice cookie_manager query for '{COOKIE_NAME}' @ {COOKIE_URL}: found {alice_hits} match(es)"
    );

    // STEP 7: verify cookie is ABSENT in Bob's store.
    // CEF does not invoke the CookieVisitor callback when the URL has no
    // matching cookies in the store (even when visit_url_cookies returns 1 /
    // "queued"). We use a settle window: if the flag is not set within 3 s of
    // pumping, there are no cookies (absence confirmed by silence).
    let (b_visit_done, b_count) = schedule_visit_cookies(&bob_mgr);
    pump_until_or_settle(&engine, &b_visit_done, 3_000);
    let bob_hits = b_count.load(Ordering::Acquire);
    eprintln!(
        "bob   cookie_manager query for '{COOKIE_NAME}' @ {COOKIE_URL}: found {bob_hits} match(es)"
    );

    // Results.
    let alice_ok = alice_hits >= 1;
    let bob_ok = bob_hits == 0;

    println!("\n================ COOKIE ISOLATION PROOF ================");
    println!(
        "Cookie '{COOKIE_NAME}' in alice's store: {} (expected: PRESENT)",
        if alice_ok {
            "PRESENT"
        } else {
            "ABSENT — FAIL"
        }
    );
    println!(
        "Cookie '{COOKIE_NAME}' in bob's store:   {} (expected: ABSENT)",
        if bob_ok {
            "ABSENT"
        } else {
            "PRESENT — ISOLATION FAILURE"
        }
    );
    println!("---------------------------------------------------------");
    println!(
        "COOKIE ISOLATION: {}",
        if alice_ok && bob_ok { "PASS" } else { "FAIL" }
    );
    println!("=========================================================\n");

    if !alice_ok {
        eprintln!(
            "FAIL: alice's own cookie was not found — set_cookie may have failed \
             or the wrong URL was queried"
        );
    }
    if !bob_ok {
        eprintln!(
            "ISOLATION FAILURE: cookie set in alice leaked into bob's cookie store. \
             This means the two RequestContexts are sharing a cookie store — \
             the profile isolation substrate is broken. MUST-level finding."
        );
    }

    // Cleanup.
    engine.shutdown();

    if alice_ok && bob_ok {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    }
}
